### ISSUE TITLE
Running 'Get' commands the script clears the console 

### ISSUE THREAD

**Issue by jpsider** [arielsanchezmora/vDocumentation#11]
Current behavior: When running Get commands the script first clears the console, then runs the script.
Desired behavior: Do not clear the screen. 

This is more of a personal preference, I think if a user wants to clear the screen, they can go ahead and do that, I tend to like the ability to scroll up to view a previous run of the script.

Solution: Remove 'Clear-Host' from line 140,596,959,1658 (all occurrences I found).

**Comment by Freepeh** [comment]
I second this as well, no need to clear-host.  I too prefer this behavior removed.

**Comment by edmsanchez** [comment]
Got it. Great feedback will fix on next release

**Comment by arielsanchezmora** [comment]
I've merged @jpsider 's change for this issue
