### ISSUE TITLE
Create '-PassThru' option

### ISSUE THREAD

**Issue by jpsider** [arielsanchezmora/vDocumentation#13]
Current Behavior: Return to console is Text based
Desired Behavior: Return Object to console

Adding a '-PassThru' option will allow the user to capture the console return as an object for further manipulation.

I'll be creating a pull request soon.

**Comment by edmsanchez** [comment]
Great feedback; currently working on v2.00 release; will include this update

**Comment by arielsanchezmora** [comment]
I've merged @jpsider 's change for this issue
