### ISSUE TITLE
VMHostNeworkInfo type is deprecated

### ISSUE THREAD

**Issue by DaveBF** [arielsanchezmora/vDocumentation#16]
In the Get-ESXNetworking command, the following warning is reported.
WARNING: The 'VirtualNic' property of VMHostNetworkInfo type is deprecated. Use 'Get-VMHostNetworkAdapter' cmdlet instead.

Running PowerCLI 6.5 Release 1.

**Comment by arielsanchezmora** [comment]
I did see this. @edmsanchez do we have an alternate way of doing it? We can ask Kyle Ruddy

**Comment by edmsanchez** [comment]
Thanks for the feedback... for some reason I had set to false deprecationwarnings :(. Thank you for pointing it out ill update the code to use Get-VMHostNetworkAdapter instead; will get updated on next minor release

**Comment by edmsanchez** [comment]
v2.1.0 released today includes this fix. Thanks

**Comment by arielsanchezmora** [comment]
I believe this one can be closed since v2.1.0. Please test a newer version and let us know? Closing the issue :)
