### ISSUE TITLE
combine all the excel outputs from all four commands into a single excel

### ISSUE THREAD

**Issue by akozlow** [arielsanchezmora/vDocumentation#17]
Hi,

I love the script and the function.  They work great, but I really would like a what of combining all of the into one excel for ease.

How can I do that?

**Comment by akozlow** [comment]
nevermind, figured it out.  Just had to make sure that the output file parameter is the same for each and then remove the + date.  worked like a charm

**Comment by arielsanchezmora** [comment]
Oooh I didn't know we could do this! @edmsanchez take a look :) thank you @akozlow !!

**Comment by akozlow** [comment]
No problem, I am newbie with powercli and CLI in general because I feared it.  No more, our architect told me if i wanted to be an architect in the future, I needed to be very proficient with CLI.  That is what I am doing.  I love the scripts you provide. I am a big fan of GIT and will comment on this project as needed.

**Comment by edmsanchez** [comment]
great hack @akozlow !!
