### ISSUE TITLE
Add SSH information

### ISSUE THREAD

**Issue by akozlow** [arielsanchezmora/vDocumentation#19]
Could we include whether the SSH service is running and if the disable shell warning is also enabled?

I am attempting to add it to a copy of the script.  Also, any NFS settings in the advanced settings.

**Comment by jpsider** [comment]
I think this is more of a Vester type of item. Two different tools doing similar but very different things. Give it a look:
https://github.com/WahlNetwork/Vester

**Comment by edmsanchez** [comment]
SSH seriver and ESXi Shell service details have been added to v2.1.0 released today. That should have what you were looking for, any questions/feedback let us know.

**Comment by arielsanchezmora** [comment]
Seems this is now included, since v2.1.0 - could you check and reopen an issue if needed? Thanks, closing this one now.
