### ISSUE TITLE
Update Module Scaffolding

### ISSUE THREAD

**Issue by jpsider** [arielsanchezmora/vDocumentation#25]
Ideally it would be awesome to get this in a CI/CD pipeline. I suggest (and will add a PR) updating to a new scaffolding that will jive directly with AppVeyor. 

This will auto-deploy (when desired) to the PS gallery.

Each commit will build in appveyor and report any findings.

Also update the module and functions to pass PSScriptAnalyzer.

**Comment by arielsanchezmora** [comment]
Sadly, this really did fly over our heads. I'll talk with @edmsanchez but clearly we'll need to talk more with you :)
