### ISSUE TITLE
Get-TimeZone is not recognized

### ISSUE THREAD

**Issue by SupraOva** [arielsanchezmora/vDocumentation#30]
In the Get-ESXInventory command, the following error is reported.

> Get-TimeZone : The term 'Get-TimeZone' is not recognized as the name of a
> cmdlet, function, script file, or operable program. Check the spelling of the
> name, or if a path was included, verify that the path is correct and try again.
> At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\vDocumentation\Public\Get
> -ESXInventory.ps1:399 char:30
>              $localTimeZone = Get-TimeZone
>                               ~~~~~~~~~~~~
>      CategoryInfo          : ObjectNotFound: (Get-TimeZone:String) [], Comman
>    dNotFoundException
>      FullyQualifiedErrorId : CommandNotFoundException
> 
> Exception calling "ConvertTime" with "2" argument(s): "Value cannot be null.
> Parameter name: destinationTimeZone"
> At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\vDocumentation\Public\Get
> -ESXInventory.ps1:400 char:13
>              $BootTime = [System.TimeZoneInfo]::ConvertTime($bootTimeUTC,
> $localT ...
> ~~~~~~~~~~~~
> CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> FullyQualifiedErrorId : ArgumentNullException

## Solved 

Line 399, replace :
NOK : $localTimeZone = Get-TimeZone
OK  : **$localTimeZone = (Get-WmiObject win32_timezone).StandardName**

Add line 400 : 
**$SystemTimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById($localTimeZone)**

Replace line 401 :
NOK : $BootTime = [System.TimeZoneInfo]::ConvertTime($bootTimeUTC, $localTimeZone)
OK  : **$BootTime = [System.TimeZoneInfo]::ConvertTime($bootTimeUTC, $SystemTimeZone)**

Hope this helps :)

PowerCLI : 6.5 Release 1 build 4624819
vDocumentation : 2.1.0

**Comment by ArbrOizo** [comment]
Hello,

Get-TimeZone cmdlet is available with and since PowerShell 5.1.

Thanks for your workaround which will help for previous versions.

**Comment by arielsanchezmora** [comment]
Oh, I didn't know this. @edmsanchez what do you think? We have said the requirement is PowerShell 5.x but the timezone function is only available after 5.1

**Comment by edmsanchez** [comment]
this should be fixed in latest release. If you are still having problems on v2.4.3 or later let us know

**Comment by arielsanchezmora** [comment]
Cool, I'll close
