### ISSUE TITLE
Get-VMHost did twice

### ISSUE THREAD

**Issue by OlivierFaucon** [arielsanchezmora/vDocumentation#31]
Hello,

Very nice scripts, many thanks.

I notice that, except when parameter _esxi_ is chosen, the _Get-VMHost_ is done twice.
Once, creating the _$vHostList_ or the _$tempList_, and afterwards getting _$vmhost_.
I would suggest to keep it as it is for parameters _datacenter_ and _cluster_, and modify the _$vHostList_ for _ESXi_ parameter :
       foreach ($invidualHost in $esxi) {
            _# $vHostList += $invidualHost.Trim() | Sort-Object -Property Name_
            **$vHostList += $invidualHost.Trim()**
        } #END foreach
	#
	**$vHostList = Get-VMHost -Name $vHostList  | Sort-Object -Property Name**
	#
  
And change the _foreach_ loop :
	_# foreach ($esxihost in $vHostList) {_
	**foreach ($vmhost in $vHostList) {**

and replace _$esxihost_ by **$vmhost** in the  _$skipCollection_ and _$esxcli2_ :
            $skipCollection += [pscustomobject]@{
               _# 'Hostname'         = $esxihost_
               **'Hostname'         = $vmhost.name**
                _# 'Connection State' = $esxihost.ConnectionState_
                **'Connection State' = $vmhost.ConnectionState**
            } #END [PSCustomObject]
            continue
        } #END if/else
        _# $esxcli2 = Get-EsxCli -VMHost $esxihost -V2_
        **$esxcli2 = Get-EsxCli -VMHost $vmhost -V2**

When managing many vCenters with hundreds of ESXi, this modification gives faster results.

Thanks,

**Comment by arielsanchezmora** [comment]
I like this idea! @edmsanchez take a look :)

**Comment by edmsanchez** [comment]
Hi Oliver,

thanks for the feedback, this has been fixed on v2.4.1

**Comment by arielsanchezmora** [comment]
Fixed, we acknowledged you on the change log, thank you :)
