### ISSUE TITLE
Multiple vCenters

### ISSUE THREAD

**Issue by stoneisman** [arielsanchezmora/vDocumentation#34]
I would like a way to have all connected vcenters information pulled for each command. Looks like only the last one connected is polled for it's information when you execute a command. I don't see a way to iterate through all connected vcenters or specify multiple datacenters.

**Comment by arielsanchezmora** [comment]
Hi! Yup, sounds useful. I *think* we had a way. @edmsanchez do you remember?

**Comment by arielsanchezmora** [comment]
I've confirmed this works for me and others, please let us know if you couldn't find the DefaultVIServer variable in PowerCLI and we'll help (maybe in the #vdocumentation channel in the public VMware Code Slack?) but I'll close this one.
