### ISSUE TITLE
Missing RAC details

### ISSUE THREAD

**Issue by vPinballas** [arielsanchezmora/vDocumentation#35]
Hi guys

Found that after upgrading our hosts from ESXi 6.0 build 4600944 to ESXi 6.5 build 7388607 and running "get-esxinventory" we no longer get any "RAC IP, RAC MAC or RAC Firmware" details in the export, the collection runs without issues and just leave the fields blank.

vDocumentation version 2.4.0

Any ideas here?

Thanks

Johan

**Comment by arielsanchezmora** [comment]
Thanks @stalmon , I didn't know that! @edmsanchez check this out :)

There's a general bug with CIM in 6.5 that we told @kmruddy about - he says it may get fixed soon. We'll try to continue using the old method, which is vendor agnostic

**Comment by edmsanchez** [comment]
2 important changes on 6.5
1) https://kb.vmware.com/s/article/2148910 - WBEM services are not started/disabled by deafult
2) PowerCLI CIM session Ticket fails to authenticate with ESXi 6.5 WBEM

if you have upgraded to 6.5 then #1 is not a problem, but if its a new install then you will need to enabel that first.
for #2 is what @kmruddy had the bug opened for; I have a workaround for that... and its that you use the root credentials to query for iDRAC/iLO IPs. Given that all your hosts have the same root password then this would work - this is what I use today.

if you see this would benefit you, then I could add the workaround and publish it, it will prompt for root credentials using get-credential and those will be relayed securely... sort of the same way get-esxspeculative execution is done today.

**Comment by Pinballas** [comment]
Hi Edgar

Sorry i missed your reply earlier. All our hosts will be classified as upgrades so #1 is good to go, for #2 it would be of great help if you can share the workaround code. 
Thank you in advance

**Comment by arielsanchezmora** [comment]
I know this was fixed in 6.7 and later 6.5's - please open up a new issue with your host versions if the issue remains, since we know it's not our code that's causing this.
