### ISSUE TITLE
Module closes after executing

### ISSUE THREAD

**Issue by JamieE74** [arielsanchezmora/vDocumentation#42]
Using version 2.4.4, I connect to my vCenter, then run get-esxinventory.   It was say 'connected to xxxxx' then Gathering all hosts from the following vCenter(s).  It'll sit there for about a minute and then the PowerShell window will close.

I do not experience this with the other modules.

**Comment by arielsanchezmora** [comment]
I'll close this one as this is the only reported case and we didn't get an output to troubleshoot, but feel free to open again and give us some more data.
