### ISSUE TITLE
 VMware Compatibility Guide url

### ISSUE THREAD

**Issue by pdpelsem** [arielsanchezmora/vDocumentation#44]
Hi,
Would you considerer adding the VMware Compatibility Guide url to Get-ESXIODevice.ps1?
for example:

**$VID  = [String]::Format("{0:x4}", $device.VendorId)
            $DID  = [String]::Format("{0:x4}", $device.DeviceId)
            $SVID = [String]::Format("{0:x4}", $device.SubVendorId)
            $SSID = [String]::Format("{0:x4}", $device.SubDeviceId)
            $HCLurl = "https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&VID=$VID&DID=$DID&SVID=$SVIS&SSID=$SSID&details=1"**
            <#
              Use a custom object to store
              collected data
            #>
            $outputCollection += [PSCustomObject]@{
                'Hostname'         = $vmhost.Name
                'Slot Description' = $pciDevice.SlotDescription
                'VMKernel Name'    = $pciDevice.VMKernelName
                'Device Name'      = $pciDevice.DeviceName
                'Vendor Name'      = $pciDevice.VendorName
                'Device Class'     = $pciDevice.DeviceClassName
                'PCI Address'      = $pciDevice.Address
                'VID'              = [String]::Format("{0:x4}", $device.VendorId)
                'DID'              = [String]::Format("{0:x4}", $device.DeviceId)
                'SVID'             = [String]::Format("{0:x4}", $device.SubVendorId)
                'SSID'             = [String]::Format("{0:x4}", $device.SubDeviceId)
                'Driver'           = $pciDevice.ModuleName
                'Driver Version'   = $driverVersion
                'Firmware Version' = $firmwareVersion
                'VIB Name'         = $vibName
                'VIB Version'      = $vibVersion
                **'HCLurl'           = $HCLurl**
            } #END [PSCustomObject]

**Comment by edmsanchez** [comment]
@pdpelsem v2.4.6 is out, go ahead and test with that and give us feedback.

**Comment by arielsanchezmora** [comment]
this was added and has been tweaked for maximum compatibility in subsequent releases. thanks again, I'll add you in the changelog comments!
