### ISSUE TITLE
Get-ESXIODevice errors on some vCenters

### ISSUE THREAD

**Issue by skostmayer** [arielsanchezmora/vDocumentation#48]
First - Great job!  Second on to my issue.  I am running the 2.4.7 version of your script and continue to see an error at line 314 char 9, which appears to be this line:
$pciDevices = $esxcli.hardware.pci.list.Invoke() | Where-Object {$_.VMKernelName -like "vmhba*" -or $_.VMKernelName -like "vmnic*" -or $_.VMKernelName -like "vmgfx*"} | Sort-Object -Property VMKernelName 

Example:
 Gathering information from usndcesx.us.deloitte.com ...
Object of type 'InternalVimApi_50.ManagedObjectReference' cannot be converted to type 'System.String'.
At C:\Users\xxx\Documents\WindowsPowerShell\Modules\vDocumentation\2.4.7\Public\Get-ESXIODevice.ps1:314 char:9
+         $pciDevices = $esxcli.hardware.pci.list.Invoke() | Where-Obje ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException

Errors repeats for all hosts in this vCenter. Seen this issue?

**Comment by arielsanchezmora** [comment]
Hi, I haven't! What version of esxi host, vCenter, and powercli? cc @edmsanchez

**Comment by skostmayer** [comment]
This is a non-issue.  I have not seen this problem again.  thanks!
